# Twitter: @tereza_tizkova
# Fun Fact: I am boring.

print("      *     *                    ")
print("                      *          ")
print("*         *                 *    ")
print("     *           *     *         ")
print("           HHHHHHH        *      ")
print(" *         HHHHHHH               ")
print("     *   HHHHHHHHHHH    *     *  ")
print("         *   @ @   *             ")
print("        *     ^     *            ")
print("  *       *       *         *    ")
print("         SSS * * S               ")
print("         * SSSSSSSS *            ")
print("       *      O   SS  *          ")
print("      *       O    S   *         ")
print("      *       O        *         ")
print("       *              *          ")
print("           *   *   *             ")
